# Generated by Django 5.0.6 on 2024-07-13 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_ticket_historicalticket_event_tickets_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalparticipant',
            name='amount_of_people',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='amount_of_people',
        ),
    ]
