# Generated by Django 5.0.6 on 2024-07-13 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_historicalparticipant_amount_of_people_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='tickets',
        ),
        migrations.RemoveField(
            model_name='historicalevent',
            name='tickets',
        ),
        migrations.AddField(
            model_name='historicalticket',
            name='event',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='events.event', verbose_name='Event'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='events.event', verbose_name='Event'),
            preserve_default=False,
        ),
    ]
