# Generated by Django 5.0.6 on 2024-07-13 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_event_tickets_remove_historicalevent_tickets_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalparticipant',
            name='attended',
            field=models.BooleanField(verbose_name='Attended'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='attended',
            field=models.BooleanField(verbose_name='Attended'),
        ),
    ]
