# Generated by Django 5.0.6 on 2024-07-15 15:03

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_historicalparticipant_attended_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.RemoveField(
            model_name='historicalevent',
            name='location',
        ),
        migrations.AddField(
            model_name='event',
            name='google_maps_embed_url',
            field=models.URLField(max_length=512, default='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2509.42502828177!2d3.138836176488329!3d51.02677024570109!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47c34bca78f25ab3%3A0x616de4a63f576ab8!2sCultuurhuis%20Cinema%20De%20Keizer!5e0!3m2!1snl!2sbe!4v1721054745033!5m2!1snl!2sbe', verbose_name='Google Maps embed URL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default='a', upload_to='events', verbose_name='Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='location_long',
            field=ckeditor.fields.RichTextField(default='Cinema De Keyser', verbose_name='Location (long)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='location_short',
            field=models.CharField(default='Cinema De Keizer', max_length=50, verbose_name='Location (short)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='google_maps_embed_url',
            field=models.URLField(max_length=512, default='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2509.42502828177!2d3.138836176488329!3d51.02677024570109!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47c34bca78f25ab3%3A0x616de4a63f576ab8!2sCultuurhuis%20Cinema%20De%20Keizer!5e0!3m2!1snl!2sbe!4v1721054745033!5m2!1snl!2sbe', verbose_name='Google Maps embed URL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='image',
            field=models.TextField(default='a', max_length=100, verbose_name='Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='location_long',
            field=ckeditor.fields.RichTextField(default='s', verbose_name='Location (long)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='location_short',
            field=models.CharField(default='s', max_length=50, verbose_name='Location (short)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Description'),
        ),
    ]
