# Generated by Django 5.0.6 on 2024-07-17 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_participant_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'get_latest_by': 'pk'},
        ),
    ]
