# Generated by Django 5.0.6 on 2024-07-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_event_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalparticipant',
            name='random_seed',
            field=models.CharField(default='a', editable=False, max_length=10, verbose_name='Random Seed'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='random_seed',
            field=models.CharField(default='a', editable=False, max_length=10, verbose_name='Random Seed'),
            preserve_default=False,
        ),
    ]
