# Generated by Django 5.0.6 on 2024-07-22 17:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_historicalparticipant_random_seed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='email_text',
            field=ckeditor.fields.RichTextField(default='test', verbose_name='Email Text'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='email_text',
            field=ckeditor.fields.RichTextField(default='test', verbose_name='Email Text'),
            preserve_default=False,
        ),
    ]
