# Generated by Django 5.0.6 on 2024-07-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_alter_historicalpayment_status_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpayment',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Open', 'Open'), ('Canceled', 'Canceled'), ('Expired', 'Expired'), ('Failed', 'Failed')], default='Open', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Open', 'Open'), ('Canceled', 'Canceled'), ('Expired', 'Expired'), ('Failed', 'Failed')], default='Open', max_length=10),
        ),
    ]
