services:

  web:
    pull_policy: always
    build:
      context: .
      dockerfile: Dockerfile
    command: python saranalaya/manage.py runserver 0.0.0.0:8100
    restart: always
    volumes:
      - .:/code
    ports:
      - "8100:8100"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
      
  db:
    image: postgres
    container_name: saranalaya_db
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - "5433"
    ports:
      - 5433:5433

  adminer:
    container_name: saranalaya_adminer_container
    image: adminer
    restart: unless-stopped
    ports:
      - 8081:8081
    depends_on:
      - db
