services:

  web:
    build: .
    pull_policy: build
    command: python manage.py runserver 0:8100
    restart: always
    env_file: stack.env

    volumes:
      - .:/data
      - media_volume:/code/media
    ports:
      - "8100:8100"
    depends_on:
      - db
      
  db:
    image: postgres:16
    container_name: saranalaya_db
    restart: always
    env_file: stack.env

    volumes:
      - ./data/db:/var/lib/postgresql/data
    expose:
      - "5433"
    ports:
      - 5433:5433

  backup:
    image: eeshugerman/postgres-backup-s3:16
    env_file: stack.env
    environment:
      SCHEDULE: '@daily'
      BACKUP_KEEP_DAYS: 14

volumes:
  postgres_date:
  media_volume: