services:

  web:
    build: .
    pull_policy: build
    command: python manage.py runserver 0:8100
    restart: always
    env_file: stack.env

    volumes:
      - .:/data
    ports:
      - "8100:8100"
    depends_on:
      - db
      
  db:
    image: postgres:16
    container_name: saranalaya_db
    restart: always
    env_file: stack.env

    volumes:
      - ./data/db:/var/lib/postgresql/data
    expose:
      - "5433"
    ports:
      - 5433:5433

  adminer:
    container_name: saranalaya_adminer_container
    image: adminer
    restart: unless-stopped
    env_file: stack.env

    ports:
      - 8081:8081
    depends_on:
      - db
