# Generated by Django 5.0.2 on 2024-02-18 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('firm', models.CharField(blank=True, max_length=45, null=True)),
                ('street_name', models.CharField(max_length=100)),
                ('address_number', models.IntegerField()),
                ('bus', models.IntegerField(blank=True, null=True)),
                ('postcode', models.IntegerField()),
                ('city', models.CharField(max_length=40)),
                ('country', models.CharField(default='Belgium', max_length=40)),
                ('mail', models.EmailField(max_length=254)),
                ('description', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Adoption Parent',
                'verbose_name_plural': 'Adoption Parents',
                'ordering': ['last_name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=1)),
                ('day_of_birth', models.DateField()),
                ('date_of_admission', models.DateField()),
                ('date_of_leave', models.DateField(blank=True, null=True)),
                ('indian_parent_status', models.CharField(choices=[('n', 'No Parents'), ('o', 'One Parent'), ('t', 'Two Parents')], max_length=1, verbose_name='Indian Parent Status')),
                ('status', models.CharField(choices=[('a', 'Active'), ('l', 'Left'), ('s', 'Support')], max_length=1)),
                ('link_website', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Child',
                'verbose_name_plural': 'Children',
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('firm', models.CharField(blank=True, max_length=45, null=True)),
                ('street_name', models.CharField(max_length=100)),
                ('address_number', models.IntegerField()),
                ('bus', models.IntegerField(blank=True, null=True)),
                ('postcode', models.IntegerField()),
                ('city', models.CharField(max_length=40)),
                ('country', models.CharField(default='Belgium', max_length=40)),
                ('mail', models.EmailField(max_length=254)),
                ('description', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True)),
            ],
            options={
                'verbose_name': 'Sponsor',
                'verbose_name_plural': 'Sponsors',
                'ordering': ['last_name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdoptionParentSponsoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='admin_app.adoptionparent')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='admin_app.child')),
            ],
            options={
                'verbose_name': 'Adoption Parent Payment',
                'verbose_name_plural': 'Adoption Parent Payments',
            },
        ),
        migrations.AddField(
            model_name='adoptionparent',
            name='children',
            field=models.ManyToManyField(blank=True, to='admin_app.child'),
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='admin_app.sponsor')),
            ],
            options={
                'verbose_name': 'Donation',
                'verbose_name_plural': 'Donations',
            },
        ),
    ]
