# Generated by Django 5.0.2 on 2024-02-17 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('firm', models.CharField(blank=True, max_length=45)),
                ('address', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=254)),
                ('description', models.TextField(blank=True)),
                ('phone_number', models.CharField(max_length=12)),
            ],
            options={
                'ordering': ['last_name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=1)),
                ('day_of_birth', models.DateField()),
                ('date_of_admission', models.DateField()),
                ('date_of_leave', models.DateField(blank=True)),
                ('parent_status', models.CharField(choices=[('n', 'No Parents'), ('o', 'One Parent'), ('t', 'Two Parents')], max_length=1)),
                ('status', models.CharField(choices=[('a', 'Active'), ('l', 'Left'), ('s', 'Support')], max_length=1)),
                ('link_website', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('firm', models.CharField(blank=True, max_length=45)),
                ('address', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=254)),
                ('description', models.TextField(blank=True)),
                ('phone_number', models.CharField(blank=True, max_length=12)),
            ],
            options={
                'ordering': ['last_name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdoptionParentSponsoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.FloatField()),
                ('description', models.TextField(blank=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='admin_app.adoptionparent')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='admin_app.child')),
            ],
        ),
        migrations.AddField(
            model_name='adoptionparent',
            name='children',
            field=models.ManyToManyField(to='admin_app.child'),
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='admin_app.sponsor')),
            ],
        ),
    ]
