# Generated by Django 3.2.25 on 2024-06-29 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adoptionparentsponsoring',
            options={'get_latest_by': 'date', 'verbose_name': 'Adoption Parent Payment', 'verbose_name_plural': 'Adoption Parent Payments'},
        ),
        migrations.AlterField(
            model_name='adoptionparent',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='adoptionparent',
            name='address_number',
            field=models.IntegerField(verbose_name='Address Number'),
        ),
        migrations.AlterField(
            model_name='adoptionparent',
            name='bus',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Bus'),
        ),
        migrations.AlterField(
            model_name='adoptionparent',
            name='children',
            field=models.ManyToManyField(blank=True, to='admin_app.Child', verbose_name='Children'),
        ),
        migrations.AlterField(
            model_name='adoptionparent',
            name='city',
            field=models.CharField(max_length=40, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='adoptionparent',
            name='country',
            field=models.CharField(default='Belgium', max_length=40, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='adoptionparent',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='adoptionparent',
            name='firm',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Firm'),
        ),
        migrations.AlterField(
            model_name='adoptionparent',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='adoptionparent',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='adoptionparent',
            name='mail',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='adoptionparent',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='adoptionparent',
            name='postcode',
            field=models.CharField(max_length=15, verbose_name='Postcode'),
        ),
        migrations.AlterField(
            model_name='adoptionparent',
            name='street_name',
            field=models.CharField(max_length=100, verbose_name='Street Name'),
        ),
        migrations.AlterField(
            model_name='adoptionparentsponsoring',
            name='amount',
            field=models.FloatField(verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='adoptionparentsponsoring',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='admin_app.child', verbose_name='Child'),
        ),
        migrations.AlterField(
            model_name='adoptionparentsponsoring',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='adoptionparentsponsoring',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='adoptionparentsponsoring',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='admin_app.adoptionparent', verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='child',
            name='date_of_admission',
            field=models.DateField(verbose_name='Date of Admission'),
        ),
        migrations.AlterField(
            model_name='child',
            name='date_of_leave',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Leave'),
        ),
        migrations.AlterField(
            model_name='child',
            name='day_of_birth',
            field=models.DateField(verbose_name='Day of Birth'),
        ),
        migrations.AlterField(
            model_name='child',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='child',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=1, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='child',
            name='link_website',
            field=models.URLField(blank=True, null=True, verbose_name='Link website'),
        ),
        migrations.AlterField(
            model_name='child',
            name='name',
            field=models.CharField(max_length=60, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='child',
            name='status',
            field=models.CharField(choices=[('a', 'Active'), ('l', 'Left'), ('s', 'Support')], max_length=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.FloatField(verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='admin_app.sponsor', verbose_name='Sponsor'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='address_number',
            field=models.IntegerField(verbose_name='Address Number'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='bus',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Bus'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='city',
            field=models.CharField(max_length=40, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='country',
            field=models.CharField(default='Belgium', max_length=40, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='firm',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Firm'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='mail',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='postcode',
            field=models.CharField(max_length=15, verbose_name='Postcode'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='street_name',
            field=models.CharField(max_length=100, verbose_name='Street Name'),
        ),
    ]
