# Generated by Django 5.0.2 on 2024-02-17 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adoptionparent',
            options={'ordering': ['last_name'], 'verbose_name': 'Adoption Parent', 'verbose_name_plural': 'Adoption Parents'},
        ),
        migrations.AlterModelOptions(
            name='adoptionparentsponsoring',
            options={'verbose_name': 'Adoption Parent Sponsoring', 'verbose_name_plural': 'Adoption Parent Sponsorings'},
        ),
        migrations.AlterModelOptions(
            name='child',
            options={'verbose_name': 'Child', 'verbose_name_plural': 'Children'},
        ),
        migrations.AlterModelOptions(
            name='donation',
            options={'verbose_name': 'Donation', 'verbose_name_plural': 'Donations'},
        ),
        migrations.AlterModelOptions(
            name='sponsor',
            options={'ordering': ['last_name'], 'verbose_name': 'Sponsor', 'verbose_name_plural': 'Sponsors'},
        ),
    ]
