# Generated by Django 5.0.2 on 2024-02-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_alter_adoptionparent_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptionparent',
            name='children',
            field=models.ManyToManyField(blank=True, to='admin_app.child'),
        ),
    ]
