# Generated by Django 5.0.6 on 2024-07-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_alter_historicaladoptionparent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='letters',
            field=models.BooleanField(default=True, verbose_name='Letters'),
        ),
    ]
