# Generated by Django 5.0.6 on 2024-08-06 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_sponsor_letters'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='child',
            options={'ordering': ['name', 'day_of_birth'], 'verbose_name': 'Child', 'verbose_name_plural': 'Children'},
        ),
    ]
