# Generated by Django 5.0.2 on 2024-02-18 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0006_alter_adoptionparent_children'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionparent',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
