# Generated by Django 5.0.6 on 2024-08-06 18:51

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0006_alter_child_options'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adoptionparent',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name': 'Adoption Parent', 'verbose_name_plural': 'Adoption Parents'},
        ),
        migrations.AlterModelOptions(
            name='sponsor',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name': 'Sponsor', 'verbose_name_plural': 'Sponsors'},
        ),
        migrations.AddField(
            model_name='adoptionparent',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='adoptionparentsponsoring',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='child',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='historicaladoptionparent',
            name='last_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 8, 6, 18, 50, 56, 38985), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaladoptionparentsponsoring',
            name='last_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 8, 6, 18, 51, 2, 4089), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalchild',
            name='last_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 8, 6, 18, 51, 8, 932147), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaldonation',
            name='last_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 8, 6, 18, 51, 13, 158532), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalsponsor',
            name='last_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 8, 6, 18, 51, 18, 524216), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sponsor',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='UserView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('last_viewed', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'content_type', 'object_id')},
            },
        ),
    ]
