# Generated by Django 5.1.3 on 2025-02-06 10:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0008_sponsor_letters_adoption_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelNotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255, unique=True)),
                ('subscribers', models.ManyToManyField(blank=True, related_name='receiving_notifications', to=settings.AUTH_USER_MODEL)),
                ('watched_users', models.ManyToManyField(blank=True, related_name='triggering_notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
