# Generated by Django 5.1.3 on 2025-02-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0009_sponsor_letters_modelnotificationpreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelnotificationpreference',
            name='model_name',
            field=models.CharField(choices=[('child', 'Child'), ('ad_parent', 'Adoption Parent'), ('adoption', 'Adoption'), ('ap_sponsoring', 'Adoption Parent Payment'), ('sponsor', 'Sponsor'), ('donation', 'Donation')], max_length=32, verbose_name='Model'),
        ),
        migrations.DeleteModel(
            name='UserView',
        ),
    ]
