# Generated by Django 5.1.3 on 2025-02-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0010_sponsor_letters_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adoption',
            options={'verbose_name': 'Adoption', 'verbose_name_plural': 'Adoptions'},
        ),
        migrations.AlterField(
            model_name='modelnotificationpreference',
            name='model_name',
            field=models.CharField(choices=[('Child', 'Child'), ('Adoption Parent', 'Adoption Parent'), ('Adoption', 'Adoption'), ('Adoption Parent Payment', 'Adoption Parent Payment'), ('Sponsor', 'Sponsor'), ('Donation', 'Donation')], max_length=32, verbose_name='Model'),
        ),
    ]
