# Generated by Django 5.1.3 on 2025-03-02 18:31

import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0011_alter_adoption_options_sponsor_letters_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Content')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('image', models.ImageField(upload_to='news/', verbose_name='Image')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
                'ordering': ['-date'],
            },
        ),
        migrations.RemoveField(
            model_name='child',
            name='link_website',
        ),
        migrations.RemoveField(
            model_name='historicalchild',
            name='link_website',
        ),
        migrations.AddField(
            model_name='child',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='children/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='child',
            name='show_on_website',
            field=models.BooleanField(default=True, verbose_name='Show on Website'),
        ),
        migrations.AddField(
            model_name='child',
            name='website_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Website Description'),
        ),
        migrations.AddField(
            model_name='historicalchild',
            name='image',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='historicalchild',
            name='show_on_website',
            field=models.BooleanField(default=True, verbose_name='Show on Website'),
        ),
        migrations.AddField(
            model_name='historicalchild',
            name='website_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Website Description'),
        ),
        migrations.CreateModel(
            name='HistoricalNews',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Content')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('image', models.TextField(max_length=100, verbose_name='Image')),
                ('last_updated', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'History',
                'verbose_name_plural': 'historical News',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
