# Generated by Django 5.1.3 on 2025-03-03 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0012_news_remove_child_link_website_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnews',
            name='show_on_website',
            field=models.BooleanField(default=True, verbose_name='Show on Website'),
        ),
        migrations.AddField(
            model_name='news',
            name='show_on_website',
            field=models.BooleanField(default=True, verbose_name='Show on Website'),
        ),
    ]
