# Generated by Django 5.1.3 on 2025-03-16 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0013_historicalnews_show_on_website_news_show_on_website_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='show_on_website',
            field=models.BooleanField(default=False, verbose_name='Show on Website'),
        ),
        migrations.AlterField(
            model_name='historicalchild',
            name='show_on_website',
            field=models.BooleanField(default=False, verbose_name='Show on Website'),
        ),
        migrations.CreateModel(
            name='ExtraImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='children/', verbose_name='Image')),
                ('date', models.DateField(auto_now=True, verbose_name='Date of picture')),
                ('extra_info', models.CharField(blank=True, null=True, verbose_name='Extra Info')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='admin_app.child')),
            ],
            options={
                'verbose_name': 'Extra Image',
                'verbose_name_plural': 'Extra Images',
            },
        ),
    ]
