# Generated by Django 5.1.3 on 2025-03-16 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0014_sponsor_letters_alter_child_show_on_website_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraimage',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Date of picture'),
        ),
    ]
