# Generated by Django 5.1.3 on 2025-03-16 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0015_sponsor_letters_alter_extraimage_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiblingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
        ),
        migrations.AddField(
            model_name='child',
            name='sibling_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='siblings', to='admin_app.siblinggroup'),
        ),
        migrations.AddField(
            model_name='historicalchild',
            name='sibling_group',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='admin_app.siblinggroup'),
        ),
    ]
