# Generated by Django 5.1.3 on 2025-03-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0016_siblinggroup_sponsor_letters_child_sibling_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='status',
            field=models.CharField(choices=[('a', 'Active'), ('s', 'Support'), ('l', 'Left')], max_length=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicalchild',
            name='status',
            field=models.CharField(choices=[('a', 'Active'), ('s', 'Support'), ('l', 'Left')], max_length=1, verbose_name='Status'),
        ),
    ]
