# Generated by Django 5.1.3 on 2025-03-21 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0017_sponsor_letters_alter_child_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildTrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trait_choice', models.CharField(choices=[('c', 'Color'), ('f', 'Food'), ('a', 'Animal'), ('am', 'Ambition'), ('h', 'Hobby'), ('s', 'Subject')], max_length=2, verbose_name='Trait Choice')),
                ('text', models.CharField(max_length=255, verbose_name='Text')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traits', to='admin_app.child', verbose_name='Child')),
            ],
        ),
    ]
